name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    branches:
        - main
    
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
