name: Non Default Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      Universe:
        type: string
        required: false
        
      monitor:
          type: string
          required: false

concurrency:
  group: ${{ github.workflow }}-${{github.ref}}
  cancel-in-progress: false
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Install boto3 for python file
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::058264087706:role/TestRole
          role-session-name: sparkSecretsSession
          aws-region: ap-south-1

    - name: Printing using sh
      run: |
         chmod +x ./list_buckets.sh
         ./list_buckets.sh
  
    - name: Printing using py
      run: |
         python test.py
        
     
        
