name: Non Default Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      Universe:
        type: string
        required: false
        
      monitor:
          type: string
          required: false
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::058264087706:role/TestRole
          role-session-name: sparkSecretsSession
          aws-region: us-east-1

    - name: Printing universe
      run: |
       text= $(python ./testConn.py )
       echo "$text"
        
