name: non default f
on: 
    workflow_dispatch:
        inputs:
         Universe:
             type: string
             required: false

                  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Printing universe
        run: echo "${{inputs.Universe}}"
   
