name: Non Default Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      Universe:
        type: string
        required: false
        
      monitor:
          type: string
          required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::54905035217:role/deployCFNResource
          role-session-name: sparkSecretsSession
          aws-region: us-east-1

    - name: Printing universe
      run: |
       text= $(python ./testConn.py )
       echo "$text"
        
