name: Alert_Recovery_Script_Execution

on:
  workflow_dispatch:
    inputs:
      function_name:
        type: string
        required: true
      AWS_REGION:
        description: 'AWS Regions (comma-separated)'
        required: false
      # Instance:
      #   description: 'Instance IDs (comma-separated)'
      #   required: false
      cluster:
        description: 'Enter value of cluster'
        default: null
        required: false
      env:
        description: 'Enter value of env'
        default: null
        required: false
        
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  Recovery_workflow:
    concurrency:
      group: ${{ github.workflow }}-${{ github.run_id }}
      cancel-in-progress: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::549050352176:role/TestingDataDog_role
            role-session-name: restartservice
            aws-region: us-east-1

      - name: print inputs
        run: |
          echo "function_name is ${{ inputs.function_name }}"
          echo "region is ${{ inputs.AWS_REGION }}"
          echo "instance is ${{ inputs.Instance }}"
          echo "cluster is ${{ inputs.cluster }}"
          echo "env is ${{ inputs.env }}"
          

      - name: Make script executable
        run: chmod +x ./recoveryScripts.sh

      - name: Run script
        run: |
          # Split the input parameters into arrays without quotes
          IFS=',' read -ra regions <<< "${{ inputs.AWS_REGION }}"
          IFS=',' read -ra instances <<< "${{ inputs.Instance }}"

          # Ensure the arrays have the same length
          # if [ ${#regions[@]} -ne ${#instances[@]} ]; then
          #   echo "Error: The number of regions does not match the number of instances."
          #   exit 1
          # fi

          for i in "${!regions[@]}"; do
            region="${regions[i]}"
            instance="${instances[i]}"
            echo "Executing ${{inputs.function_name}}"
            ./recoveryScripts.sh "${{inputs.function_name}}" "$region" "$instance" "${{inputs.cluster}}" "${{inputs.env}}" &
          done

          # Wait for all commands to finish
          wait