name: Shovel Databus Queue Execution
on:
  workflow_dispatch:
    inputs:
      function_name:
        type: string
        required: true
      AWS_REGION:
        description: 'AWS Regions (comma-separated)'
        required: false
        
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  Recovery_workflow:
    concurrency:
      group: ${{ github.workflow }}-${{ github.run_id }}
      cancel-in-progress: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::468552248569:role/TestingDataDog_role
            role-session-name: ExceutePythonscript
            aws-region: us-east-1

      - name: print inputs
        run: |
          echo "function_name is ${{ inputs.function_name }}"
          echo "region is ${{ inputs.AWS_REGION }}"

      - name: Make script executable
        run: chmod +x ./recoveryScripts.sh

      - name: Run script
        run: |
            echo "Executing ShovelAck script"
            ./recoveryScripts.sh "${{inputs.function_name}}" "$region" &
            wait