name: restart UAT_ECS service main branch
on: 
    workflow_dispatch:
        inputs:
            Universe:
                description: 'Universe to deploy'
                default: 'ci'
                type: choice
                options: [ci, cert, anon, uat, bazaar]
                required: true
        
                  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echoeing input
        run: echo "${{inputs.Universe}}"
   
