name: Workflow A

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Custom input for Workflow A'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
