name: Alert_Recovery_Script_Execution

on:
  workflow_dispatch:
    inputs:
      Universe:
        type: string
        required: false
  
      AWS_REGION:
        description: 'AWS Regions (comma-separated)'
        required: false
      Instance:
        description: 'Instance IDs (comma-separated)'
        required: false
      
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  Recovery_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::549050352176:role/TestingDataDog_role
            role-session-name: restartservice
            aws-region: eu-west-1

      - name: Make script executable
        run: chmod +x ./alertRecoveryScript.sh

      - name: Run script
        run: |
          # Split the input parameters into arrays without quotes
          IFS=',' read -ra regions <<< "${{ inputs.AWS_REGION }}"
          IFS=',' read -ra instances <<< "${{ inputs.Instance }}"

          # Ensure the arrays have the same length
          if [ ${#regions[@]} -ne ${#instances[@]} ]; then
            echo "Error: The number of regions does not match the number of instances."
            exit 1
          fi

          # Process each region and instance ID pair in parallel
          for i in "${!regions[@]}"; do
            region="${regions[i]}"
            instance="${instances[i]}"
            echo "Processing region: $region, instance: $instance"
            ./alertRecoveryScript.sh "another_aws_ssm_command" "$region" "$instance" &
          done

          # Wait for all commands to finish
          wait
