name: bv-plugins-actions
on:
  push:
    branches:
      - main

permissions:
  contents: read
  statuses: write                  
jobs:
  Run_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
            maven-version: '3.6.3'

      # - name: Maven check
      #   run: |
      #       '''mvn -e verify -Ddependency-check.skip=true'''

      - name: Set GitHub Commit Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { ${{github.GITHUB_REPOSITORY}}, ${{github.GITHUB_SHA}}, ${{github.GITHUB_RUN_ID}}, ${{github.GITHUB_SERVER_URL}} = process.env;
            const state = core.getInput('${{github.event_name}}') === 'push' ? 'success' : 'failure';
            const description = state === 'success' ? 'Build succeeded' : 'Build failed';
            await ${{github.rest.repos.createCommitStatus}}({
              owner: ${{github.GITHUB_REPOSITORY}}.split('/')[0],
              repo: ${{github.GITHUB_REPOSITORY}}.split('/')[1],
              sha: ${{github.GITHUB_SHA}},
              state: state,
              target_url: `${{github.GITHUB_SERVER_URL}}/${{github.GITHUB_REPOSITORY}}/actions/runs/${{github.GITHUB_RUN_ID}}`,
              description: description,
              context: 'ci/github-actions/build-status'
            });