name: bv-plugins-actions
on:
  push:
    branches:
      - main

permissions:
  contents: read
  statuses: write                  
jobs:
  Run_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
            maven-version: '3.6.3'

      - name: Maven check
        run: |
            mvn -e verify -Ddependency-check.skip=true

      - name: Set GitHub Commit Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const { GITHUB_RUN_ID, GITHUB_SERVER_URL } = process.env;
            const state = context.workflow_run.conclusion === 'success' ? 'success' : 'failure';
            const description = state === 'success' ? 'Build succeeded' : 'Build failed';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              target_url: `${GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${GITHUB_RUN_ID}`,
              description: description,
              context: 'ci/github-actions/build-status'
            });
