name: Restart service

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'AWS Regions (comma-separated)'
        required: true
      Instance:
        description: 'Instance IDs (comma-separated)'
        required: true
      Universe:
        type: string
        required: false

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  run-ssm-command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region-instance: []
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process Inputs
        id: process-inputs
        run: |
          IFS=',' read -ra regions <<< "${{ inputs.AWS_REGION }}"
          IFS=',' read -ra instances <<< "${{ inputs.Instance }}"

          if [ ${#regions[@]} -ne ${#instances[@]} ]; then
            echo "Error: The number of regions does not match the number of instances."
            exit 1
          fi

          matrix_entries=""

          for i in "${!regions[@]}"; do
            region="${regions[i]}"
            instance="${instances[i]}"
            matrix_entries="$matrix_entries\n      - region: $region\n        instance: $instance"
          done

          echo "matrix:region-instance: [$matrix_entries]" >> $GITHUB_ENV

      - name: Set up matrix
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const env = fs.readFileSync(process.env.GITHUB_ENV, 'utf8');
            const matrix = JSON.parse(env.split('matrix: ')[1]);
            return JSON.stringify({include: matrix['region-instance']});
        id: set-matrix
        env:
          GITHUB_ENV: ${{ env.GITHUB_ENV }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::549050352176:role/TestingDataDog_role
          role-session-name: restartservice
          aws-region: ${{ matrix.region }}

      - name: Make ssmcmd.sh executable
        run: chmod +x ./ssmcmd.sh

      - name: Run SSM Command
        run: |
          region="${{ matrix.region }}"
          instance="${{ matrix.instance }}"

          echo "Processing region: $region, instance: $instance"
          ./ssmcmd.sh "$region" "$instance" &