name: bv-plugins-actions
on:
  push:
    branches:
      - main
                  
jobs:
  Run_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
            maven-version: '3.6.3'

      # - name: Maven check
      #   run: |
      #       '''mvn -e verify -Ddependency-check.skip=true'''

      - name: Set GitHub Commit Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { GITHUB_REPOSITORY, GITHUB_SHA, GITHUB_RUN_ID, GITHUB_SERVER_URL } = process.env;
            const state = core.getInput('github.event_name') === 'push' ? 'success' : 'failure';
            const description = state === 'success' ? 'Build succeeded' : 'Build failed';
            await github.rest.repos.createCommitStatus({
              owner: GITHUB_REPOSITORY.split('/')[0],
              repo: GITHUB_REPOSITORY.split('/')[1],
              sha: GITHUB_SHA,
              state: state,
              target_url: `${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}`,
              description: description,
              context: 'ci/github-actions/build-status'
            });